# Label configuration for auto-labeling PRs

dependencies:
  - changed-files:
    - any-glob-to-any-file: 'Cargo.toml'
    - any-glob-to-any-file: 'Cargo.lock'

documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
    - any-glob-to-any-file: 'docs/**/*'

ci:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**'

tests:
  - changed-files:
    - any-glob-to-any-file: 'tests/**/*'
    - any-glob-to-any-file: '**/*_test.rs'
