name: 'Install Nix'
description: 'Install Nix - works on GitHub-hosted, self-hosted, and inside containers'
author: 'FlakeCache'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  extra-conf:
    description: 'Extra nix.conf configuration lines'
    required: false
    default: ''
  flakecache:
    description: 'Enable FlakeCache binary cache (true/false)'
    required: false
    default: 'true'
  extra-substituters:
    description: 'Additional binary cache URLs (space-separated)'
    required: false
    default: ''
  extra-trusted-keys:
    description: 'Additional trusted public keys (space-separated)'
    required: false
    default: ''

outputs:
  nix-path:
    description: 'Path to Nix binary'
    value: ${{ steps.check.outputs.nix-path }}
  already-installed:
    description: 'Whether Nix was already installed'
    value: ${{ steps.check.outputs.installed }}

runs:
  using: 'composite'
  steps:
    - name: Check if Nix already installed
      id: check
      shell: bash
      run: |
        if command -v nix &> /dev/null; then
          echo "installed=true" >> $GITHUB_OUTPUT
          echo "nix-path=$(which nix)" >> $GITHUB_OUTPUT
          echo "✅ Nix already available (container mode)"
          nix --version
        else
          echo "installed=false" >> $GITHUB_OUTPUT
          echo "📦 Nix not found, will install"
        fi

    - name: Install Nix
      if: steps.check.outputs.installed == 'false'
      shell: bash
      run: |
        echo "🔧 Installing Nix..."
        curl -L https://nixos.org/nix/install | sh -s -- --no-daemon

        # Add to path for subsequent steps
        if [ -e /nix/var/nix/profiles/default/bin ]; then
          echo "/nix/var/nix/profiles/default/bin" >> $GITHUB_PATH
        fi
        if [ -e "$HOME/.nix-profile/bin" ]; then
          echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH
        fi

        # Source for current step
        [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ] && . "$HOME/.nix-profile/etc/profile.d/nix.sh"

        echo "nix-path=$(which nix)" >> $GITHUB_OUTPUT
        echo "✅ Nix installed"
        nix --version

    - name: Configure Nix
      shell: bash
      run: |
        mkdir -p ~/.config/nix

        # Build substituters list
        SUBSTITUTERS="https://cache.nixos.org"
        TRUSTED_KEYS="cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="

        # Add FlakeCache if enabled
        if [ "${{ inputs.flakecache }}" = "true" ]; then
          SUBSTITUTERS="https://c.flakecache.com $SUBSTITUTERS"
          TRUSTED_KEYS="c.flakecache.com-1:WbJFKuGbfVpBRT8FyqLrJ+EvGL6YdUrqgyj+X/FVy0I= $TRUSTED_KEYS"
          echo "📦 FlakeCache binary cache enabled"
        fi

        # Add extra substituters
        if [ -n "${{ inputs.extra-substituters }}" ]; then
          SUBSTITUTERS="${{ inputs.extra-substituters }} $SUBSTITUTERS"
        fi

        # Add extra trusted keys
        if [ -n "${{ inputs.extra-trusted-keys }}" ]; then
          TRUSTED_KEYS="${{ inputs.extra-trusted-keys }} $TRUSTED_KEYS"
        fi

        # Write config
        cat > ~/.config/nix/nix.conf << EOF
        experimental-features = nix-command flakes
        accept-flake-config = true
        substituters = $SUBSTITUTERS
        trusted-public-keys = $TRUSTED_KEYS
        fallback = true
        connect-timeout = 5
        EOF

        # Add extra config if provided
        if [ -n "${{ inputs.extra-conf }}" ]; then
          echo "${{ inputs.extra-conf }}" >> ~/.config/nix/nix.conf
        fi

        echo "✅ Nix configured with flakes enabled"
        echo "📦 Substituters: $SUBSTITUTERS"
